### PR TITLE
fix: do not set boolean flags if not defined in `argv`

### LINKED ISSUE #116: Do not set boolean to `false` if flag is not in args
Currently when defining a `boolean` option, without specifying its default value, if the user doesn't set the corresponding arg the value is set to `false`.

Therefore its impossible to know if users set the flag to `false` or this they just omitted it.

This is problematic in situation in which you want to merge the options returned by `yargs-parser` with another object options (from a config file for example) with `Object.assign` or similar.
Typically you would merge options so the CLI args take precedence  over the config file. So users can specify their config and override it in development mode by passing an option to the cli.

In such situation, if the user do not pass the flag in the CLI, the merged options will always have `false` for this flag, as `yargs-parser` option have it set to false and it override what's in the config.

Ideally the value of a boolean flag should be `undefined` when the user doesn't pass the flag in the CLI.

Would be open to a PR that implement such behavior?

### PR DESCRIPTION
**Pull request by pvdlg**
Fix #116

`boolean` flags defined without a `default` value will now behave like other option type and won't be set in the parsed results when the user doesn't set the corresponding CLI arg.

Previous behavior:
```js
var parse = require('yargs-parser');

parse('--flag', {boolean: ['flag']});
// => { _: [], flag: true }

parse('--no-flag', {boolean: ['flag']});
// => { _: [], flag: false }

parse('', {boolean: ['flag']});
// => { _: [], flag: false }
```

New behavior:
```js
var parse = require('yargs-parser');

parse('--flag', {boolean: ['flag']});
// => { _: [], flag: true }

parse('--no-flag', {boolean: ['flag']});
// => { _: [], flag: false }

parse('', {boolean: ['flag']});
// => { _: [] } => flag not set similarly to other option type
```

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -105,8 +105,10 @@ function parse (args, opts) {
   var argv = { _: [] }
 
   Object.keys(flags.bools).forEach(function (key) {
-    setArg(key, !(key in defaults) ? false : defaults[key])
-    setDefaulted(key)
+    if (key in defaults) {
```
Comment (ljharb) [inline index.js]: This should use `Object.prototype.hasOwnProperty.call`, in case the "key" is "toString" or "hasOwnProperty"

Comment (pvdlg) [reply index.js]: I kept `key in defaults` because if was there before, but I agree we should use `Object.prototype.hasOwnProperty.call`. I made the change.

**Comment by pvdlg** [comment]
Awesome! Thanks!

**Comment by pvdlg** [comment]
@bcoe could you by any chance also check out yargs/yargs#1071 which is related? Thanks!
